spring:
  application:
    name: user-center
# DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://sh-cynosdbmysql-grp-i09yebei.sql.tencentcdb.com:22683/usercenter?useSSL=false
    username: root
    password: Id2938456
  # session 失效时间
  session:
    timeout: 86400
server:
  address: 0.0.0.0


